[build]
  publish = "public"
  command = "make prepare && hugo --source demo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.57.0"

[context.deploy-preview]
  command = "hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.57.0"
